### PR TITLE
"Exotic" suggestions from @sauer2

### PR DESCRIPTION
**Pull request by ErichDonGubler**
## SGML

> I know it's basically dead and you won't find one to write a parser, but to my knowledge at least some publishers still used this format about ~5 years ago, maybe they still do. Most likely you'd do legacy support. The one repo I found seems to be dead.

I'm assuming you're talking about [`mung`](https://crates.io/crates/mung)? It doesn't even look like it parses stuff -- simple encodes/decodes some escapes, since they're similar to HTML escapes. This definitely looks like a hole...provided you can name a service or other persuasive reason to include it. :) I'd take the name of a legacy application, if you know one.

## XML

> options to control XML whitespace behavior (like for preserving whitespace)

You mean something like a style-preserving parser/emitter that, for instance, doesn't clobber input's indentation?

> options to disable all XML footguns like entity bombs

I'm not familiar with all of these. What features expose these potential risks? Is it just DTD?

## UI

Some holes have already been noted for native UI abstraction.

> offers OS callback based event handling, unlike SDL2 or SFML, offers drawing primitives, text, images, so you don't have to mess around with OpenGL, Vulkan or other low level backends,

Let's talk about what already exists in the Rust ecosystem. For example, is there a reason [`conrod`](https://docs.rs/conrod/0.57.0/conrod/) doesn't fit all of these features?

> helps with different ppi numbers?

Huh? What's that?

## PCRaster

> parser/operations API/renderer for PCRaster maps

Sounds like this is a building block for GIS, but not necessarily just for geospatial information? I guess I'm just trying to figure out what the use cases are, and if they fit under the existing GIS section.

### CODE REVIEW

**Comment by sauer2** [comment]
>I'm assuming you're talking about mung?

I was actually referring to https://github.com/tylersouthwick/rust-sgml

>This definitely looks like a hole...provided you can name a service or other persuasive reason to include it. :) I'd take the name of a legacy application, if you know one.

3B2 (some typesetting application) and probably other similar software. But let's not go that far and call it a persuasive reason to include it.

>You mean something like a style-preserving parser/emitter that, for instance, doesn't clobber input's indentation?

Right.

>I'm not familiar with all of these. What features expose these potential risks? Is it just DTD?

I'm not sure either, but most of those are probably based on (potentially embedded) DTDs.

>For example, is there a reason conrod doesn't fit all of these features?

I don't know, the lack of documentation and usage experience on my part leaves some things unclear. It's a GUI toolkit itself, though, not a library that helps building one, right?

PPI means pixel per inch, it's the DPI for screens. Such a library could for example - I think Godot and Allegro do that - offer their API calls for fake-pixel units which then get rendered correctly to the actual screen resolution.

About PCRaster: It's technically a GIS but a rather niche one and on second thought probably too exotic to be interesting for this list.

**Comment by ErichDonGubler** [comment]
> I was actually referring to https://github.com/tylersouthwick/rust-sgml

Oh, man, that code doesn't have ANY logic in it. I wouldn't even call that a library -- it's a stub, really.

I'll make an entry for this. How's it look?

> >For example, is there a reason conrod doesn't fit all of these features?
> 
> I don't know, the lack of documentation and usage experience on my part leaves some things unclear. It's a GUI toolkit itself, though, not a library that helps building one, right?

What sort of example in another language would you have in mind? I know there are libraries that serve as fundamental building blocks. For instance:

* [`rusttype`](https://crates.io/crates/rusttype)
* [`gfx`](https://crates.io/crates/gfx)

...but I guess I'm still fuzzy on the scope of what you're talking about. There are lots of UI libraries with varying depth, though there are few mature options in Rust until now.

> PPI means pixel per inch, it's the DPI for screens.

Got it. :)

> About PCRaster: It's technically a GIS but a rather niche one and on second thought probably too exotic to be interesting for this list.

👍

**Comment by sauer2** [comment]
>I'll make an entry for this. How's it look?

Solid.

>What sort of example in another language would you have in mind?

I don't thing there isn't such a thing in another language. That might also be one reason why there are so few GUI widget sets as opposed to programming languages.
Imagine something like SDL but aimed at applications instead of games. Winit might fill parts of this niche, but I don't know if it can receive events by waiting for OS callbacks.

**Comment by ErichDonGubler** [comment]
> I don't thing there isn't such a thing in another language.

Yeah, my suspicion is that most people either make the building blocks, or the finished GUI package, but not in between. I don't see much of a use case in between -- from what I see, most people willing to build GUI toolkits are willing to implement the glue for the building blocks themselves so they have a coherent system of components. 

I like the notion of "making it easier to build GUI frameworks", but I wonder if what would make it easier is providing more of the building blocks and a guide, rather than a library. The fact that there isn't such a thing already in existence makes me wonder if such a library is possible. Perhaps I could add that?

**Comment by sauer2** [comment]
>I like the notion of "making it easier to build GUI frameworks", but I wonder if what would make it easier is providing more of the building blocks and a guide, rather than a library. The fact that there isn't such a thing already in existence makes me wonder if such a library is possible. Perhaps I could add that?

That's your call. But there aren't many tutorials for stuff like this around, so it probably can't harm.

**Comment by ErichDonGubler** [comment]
@sauer2: Okay. :) Anything else you think I should fluff up before I merge things in?

**Comment by sauer2** [comment]
@ErichDonGubler Regarding SGML: Maybe instead of saying "used by older applications like 3B2" say something like "used in legacy type setting". 3B2 itself supports XML, it's just that some publishers decided on SGML instead of XML some decades ago.

**Comment by ErichDonGubler** [comment]
@sauer2: How's that look?

**Comment by sauer2** [comment]
@ErichDonGubler: It's fine, I guess.

**Comment by ErichDonGubler** [comment]
@sauer2: You guess? I'll merge this in, then -- let me know if there's anything else you want me to add or tweak. :)

**Pull request merged**
